module.exports = [
  "N/A (GA Staff)",
  "SEIF 3",
  "SEI 25",
  "UXDI 24",
  "DMI 9",
  "DSI 18",
  "UXDI 25",
  "SEIF 4",
  "SEI 26",
  "DSI 19",
  "Graduated Cohort: DSI 17",
  "Graduated Cohort: SEI 24",
  "Graduated Cohort: UXDI 23",
  "Graduated Cohort: DSI 16",
  "Others: Guest Speakers",
  "Others: Photographer",
  "Others: Clients",
  "Graduated Cohort: SEI 23",
  "Graduated Cohort: DSI 15",
  "Graduated Cohort - SEI 22",
  "Graduated Cohort - UXDI 20",
  "Graduated Cohort - DSI 14",
  "Graduated Cohort - DMI 8",
  "Graduated Cohort - DSI 15",
  "Graduated Cohort - UXDI 21",
  "Graduated Cohort - DSI 13",
];