module.exports = [
  "SEIF 5",
  "UXDI 27",
  "SEIF 4",
  "SEI 27",
  "DMI 10",
  "DSI 20",
  "UXDI 26",
  "SEI 28",
  "DSIF 1",
  "DSI 21",
  "UXDI 28",
  "Graduated Cohort: DSI 19",
  "Graduated Cohort: SEI 26",
  "Graduated Cohort: UXDI 25",
  "Graduated Cohort: DSI 18",
  "Invited Guest Speakers",
  "Invited Guest (Others)",
  "Invited Photographer",
  "Invited Project Clients",
  "Graduated Cohort - DMI 8",
  "Graduated Cohort: DSI 16",
  "Graduated Cohort: DSI 17",
  "Graduated Cohort: SEI 24",
  "Graduated Cohort: SEI 25",
  "Graduated Cohort: UXDI 23",
  "Graduated Cohort: UXDI 24",
  "Graduated Cohort: DMI 9",
  "Other Graduated Cohort",
]
